version: '3'
services:
  db:
    container_name: practicedb
    image: mysql:8.0
    # M1 Macを使用している場合は platform の指定を追加する
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  web:
    build:
      context: ./java/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: $PWD
        target: /opt/project
        consistency: cached
    # tomcatはVScodeのプラグインから立ち上げるためスリープさせておく
    command: sleep infinity
    ports:
      - "8080:8080"
      - "8005:8005"
    depends_on:
      - db
    stdin_open: true
    tty: true
volumes:
  mysql-data:
    driver: local